# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YrvruwZKcKsR9LVjYIzoWDqNMM79ZBM
"""

# Assignment 1 – Triangle Patterns
# Author: Ravish Kumar

# Lower Triangular Pattern
def lower_triangle(n):
    print("Lower Triangle Pattern:")
    for i in range(1, n + 1):
        print("* " * i)
    print()

# Upper Triangular Pattern
def upper_triangle(n):
    print("Upper Triangle Pattern:")
    for i in range(n, 0, -1):
        spaces = "  " * (n - i)
        stars = "* " * i
        print(spaces + stars)
    print()

# Pyramid Pattern
def pyramid(n):
    print("Pyramid Pattern:")
    for i in range(n):
        spaces = " " * (n - i - 1)
        stars = "* " * (i + 1)
        print(spaces + stars)
    print()

# Run all patterns for 5 rows
rows = 5
lower_triangle(rows)
upper_triangle(rows)
pyramid(rows)