# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSJqUeltG-majUQcGauH0uPvTmALtYp2
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

"""# Load Titanic dataset (ensure titanic.csv is in the same directory)
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

"""

# Load Titanic dataset (ensure titanic.csv is in the same directory)
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

# Shape and basic info
print("Shape of dataset:", df.shape)
df.info()

# Summary statistics
df.describe(include='all')

# Count of missing values
df.isnull().sum()

# Visualize missing values
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title("Missing Value Heatmap")
plt.show()

sns.histplot(df['Age'].dropna(), kde=True, bins=30, color='orange')
plt.title("Age Distribution")
plt.xlabel("Age")
plt.show()

sns.histplot(df['Fare'], kde=True, bins=40, color='green')
plt.title("Fare Distribution")
plt.xlabel("Fare")
plt.show()

sns.boxplot(x='Age', data=df)
plt.title("Age Outliers")
plt.show()

sns.boxplot(x='Fare', data=df)
plt.title("Fare Outliers")
plt.show()

numeric_data = df.select_dtypes(include=['int64', 'float64'])
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.countplot(x='Survived', hue='Sex', data=df)
plt.title("Survival by Gender")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.show()

sns.countplot(x='Survived', hue='Pclass', data=df)
plt.title("Survival by Passenger Class")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.show()

sns.countplot(x='Survived', hue='Embarked', data=df)
plt.title("Survival by Embarkation Port")
plt.xlabel("Survived (0 = No, 1 = Yes)")
plt.show()

# Step 9 – Key Insights from EDA

insights = """
🧠 Key Insights from Titanic EDA

🔍 Missing Values:
- 'Cabin' column has a significant amount of missing values.
- 'Age' has missing values that might require imputation.
- 'Embarked' has 2 missing entries.

📊 Distributions:
- Most passengers are between 20 and 40 years old.
- 'Fare' column has outliers with values exceeding $500.

📦 Outliers:
- Fare distribution is right-skewed with several high-end outliers.
- Minor outliers also present in Age.

🔗 Relationships:
- Females had a much higher survival rate compared to males.
- 1st Class passengers had better survival outcomes than 2nd and 3rd class.
- Embarked = 'C' port showed better survival rates.
- Positive correlation between Fare and Survival.

✅ Conclusion:
- Gender, passenger class, and port of embarkation significantly affected survival chances.
- Handling missing values and scaling features may be necessary before applying ML models.
"""

print(insights)